### ISSUE TITLE
panic raised by `set`

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#135]
```
» set a-b=123
panic: runtime error: index out of range

goroutine 472 [running]:
github.com/lmorg/murex/builtins/core/typemgmt.set(0xc00000c3c0, 0xc00000c3c0, 0xd348e0, 0xc00015b2b0)
        /home/lau/dev/go/src/github.com/lmorg/murex/builtins/core/typemgmt/variables.go:77 +0x83b
github.com/lmorg/murex/builtins/core/typemgmt.cmdSet(0xc00000c3c0, 0xc000092600, 0xc00032c256)
        /home/lau/dev/go/src/github.com/lmorg/murex/builtins/core/typemgmt/variables.go:29 +0x30
github.com/lmorg/murex/lang.executeProcess(0xc00000c3c0)
        /home/lau/dev/go/src/github.com/lmorg/murex/lang/process.go:296 +0x80d
created by github.com/lmorg/murex/lang.runModeNormal
        /home/lau/dev/go/src/github.com/lmorg/murex/lang/interpreter.go:163 +0x7e
```

Todo:
* [x] check if this affects other `set` commands where var name is invalid
* [x] check if this happens on `let`
* [x] check if this happens on `global`
* [x] check if this happens on `export`
* [x] write tests

**Comment by lmorg** [comment]
Problem fixed in above commits
