### ISSUE TITLE
`!pipe` can crash if named pipe is closed but hasn't finished it's timeout

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#137]
For example:

```
» pipe werew
» !pipe: werew
» !pipe: werew
panic: More closed dependants than open

goroutine 1188 [running]:
github.com/lmorg/murex/builtins/pipes/streams.(*Stdin).Close(0xc0000b6770)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/pipes/streams/define.go:79 +0x71
github.com/lmorg/murex/lang/proc/pipes.(*Named).Close(0x1933840, 0xc0007a8f20, 0x5, 0x0, 0x0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/proc/pipes/namedpipes.go:72 +0x112
github.com/lmorg/murex/builtins/core/pipe.cmdClosePipe(0xc0003ce000, 0xc00008e390, 0xc0007a8f10)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/core/pipe/pipe.go:119 +0x14b
github.com/lmorg/murex/lang.executeProcess(0xc0003ce000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/process.go:296 +0x80d
created by github.com/lmorg/murex/lang.runModeNormal
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/interpreter.go:163 +0x7e
```

Two options:
1. shorten the timeout (it is a bit excessive)
2. catch panics in `!pipe` and handle them gracefully

**Comment by lmorg** [comment]
Please note: this can only happen when both `!pipe`'s are within a few seconds of each other **and** only on the standard pipe type (it not on network or file pipes).

The reason for this is because _murex_ sets a graceful timeout after the pipe is closed on standard pipes to allow for any parallel processes writing to that pipe to clean up. ie it's a lazy way to mitigate race conditions so people writing multi-threaded _murex_ scripts don't have to worry about handling race conditions themselves.

**Comment by lmorg** [comment]
Upon a code review, the timeout was a useful feature (for the above reasons) during a prior version of the stdio's methods (back when "closed" was a boolean state). Now stdio can be passed around multiple times and when closed, an iterator is increased or decreased and reads are still permitted when the iterator is set to zero (0) - ie the pipe is "closed" (it's only writes which are denied). Thus the time out is no longer a relevant feature and in fact adds unwanted complexity. So it has been removed.
