### ISSUE TITLE
`read` panics when no parameters passed

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#142]
```
» read
panic: runtime error: slice bounds out of range

goroutine 3130 [running]:
github.com/lmorg/murex/lang/proc/parameters.Parameters.StringAllRange(0xc000404a30, 0x0, 0x1, 0xc0005e79c0, 0x1, 0x1, 0x1, 0xffffffffffffffff, 0xc000258c88, 0x40d3e9)
        /home/lau/dev/go/src/github.com/lmorg/murex/lang/proc/parameters/get.go:55 +0x14e
github.com/lmorg/murex/builtins/core/io.read(0xc0006b03c0, 0x925276, 0x3, 0x0, 0xd528c0, 0xc000158d00)
        /home/lau/dev/go/src/github.com/lmorg/murex/builtins/core/io/read.go:43 +0x406
github.com/lmorg/murex/builtins/core/io.cmdRead(0xc0006b03c0, 0xc000092540, 0xc0002506e4)
        /home/lau/dev/go/src/github.com/lmorg/murex/builtins/core/io/read.go:17 +0x49
github.com/lmorg/murex/lang.executeProcess(0xc0006b03c0)
        /home/lau/dev/go/src/github.com/lmorg/murex/lang/process.go:296 +0x80d
created by github.com/lmorg/murex/lang.runModeNormal
        /home/lau/dev/go/src/github.com/lmorg/murex/lang/interpreter.go:163 +0x7e
```

**Comment by lmorg** [comment]
Fixed in 285c26e4272c8571785e9314a039f9ffa379feed
