### ISSUE TITLE
Autocompleter crashes

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#182]
```
» rm -rv afsdfdsf
(/bin/rm) rm - remove files or directories
panic: runtime error: slice bounds out of range [-13:]

goroutine 1 [running]:
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).writeTabGrid(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/tabgrid.go:143 +0x4e9
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).writeTabCompletion(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/tab.go:82 +0x75
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).renderHelpers(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:170 +0x3d
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).updateHelpers(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:184 +0x5b
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).delete(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:122 +0x11f
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).backspace(0xc000123400)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:99 +0xba
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).Readline(0xc000123400, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/readline.go:203 +0xb3f
github.com/lmorg/murex/shell.ShowPrompt()
	/go/src/github.com/lmorg/murex/shell/shell.go:119 +0x18f
github.com/lmorg/murex/shell.Start()
	/go/src/github.com/lmorg/murex/shell/shell.go:70 +0x1d4
main.startMurex()
	/go/src/github.com/lmorg/murex/main.go:153 +0x200
main.main()
	/go/src/github.com/lmorg/murex/main.go:36 +0xca
```

**Comment by lmorg** [comment]
Issue was in vendor package. Fixed in vendors but will need to be pushed back upstream.

For reference, I do also maintain the upstream package (`lmorg/readline`). Doh!
