### ISSUE TITLE
readline: concurrent map read and map write

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#212]
```
runtime.throw(0x93ce6a, 0x21)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:617 +0x72 fp=0xc0006291f0 sp=0xc0006291c0 pc=0x42bef2
runtime.mapaccess1_faststr(0x8a8000, 0xc000090750, 0xc000364098, 0x3, 0xc0007635c0) 
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/map_faststr.go:21 +0x469 fp=0xc000629260 sp=0xc0006291f0 pc=0x412149
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).writeHintText(0xc000101180)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/hint.go:40 +0x34e fp=0xc0006293e0 sp=0xc000629260 pc=0x5a7bee
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).renderHelpers(0xc000101180)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:169 +0x2f fp=0xc000629428 sp=0xc0006293e0 pc=0x5b178f
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).Readline(0xc000101180, 0x0, 0x0, 0x0, 0x0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/readline.go:204 +0xb8f fp=0xc000629948 sp=0xc000629428 pc=0x5a993f
github.com/lmorg/murex/shell.ShowPrompt()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:119 +0x185 fp=0xc000629d58 sp=0xc000629948 pc=0x718375
github.com/lmorg/murex/shell.Start()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:70 +0x1ec fp=0xc000629de0 sp=0xc000629d58 pc=0x71808c
main.startMurex()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:153 +0x201 fp=0xc000629f60 sp=0xc000629de0 pc=0x84c2a1
main.main()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:36 +0xcb fp=0xc000629f98 sp=0xc000629f60 pc=0x84b4bb
runtime.main()
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:200 +0x20c fp=0xc000629fe0 sp=0xc000629f98 pc=0x42d85c
runtime.goexit()
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000629fe8 sp=0xc000629fe0 pc=0x4583c1

goroutine 5 [sleep, 3 minutes]:
runtime.goparkunlock(...)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:307
time.Sleep(0x45d964b800)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/time.go:105 +0x159
github.com/lmorg/murex/lang.astGarbageCollector(0xc0000903f0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/cache.go:29 +0x30
created by github.com/lmorg/murex/lang.newAstCache
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/cache.go:23 +0x54

goroutine 6 [sleep]:
runtime.goparkunlock(...)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:307
time.Sleep(0x2540be400)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/time.go:105 +0x159
github.com/lmorg/murex/lang.garbageCollection(0xc00000c240)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/variables.go:60 +0x42
created by github.com/lmorg/murex/lang.newVarTable
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/variables.go:54 +0x54

goroutine 7 [syscall, 13 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/Cellar/go/1.12.4/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/Cellar/go/1.12.4/libexec/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [syscall, 13 minutes]:
syscall.Syscall6(0xe8, 0x5, 0xc000193d14, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.4/libexec/src/syscall/asm_linux_amd64.s:44 +0x5
github.com/lmorg/murex/vendor/golang.org/x/sys/unix.EpollWait(0x5, 0xc000193d14, 0x7, 0x7, 0xffffffffffffffff, 0xc000193d10, 0x0, 0xc000001980)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1710 +0x72
github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc00002b840, 0x983100, 0xc00002b840, 0x0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify/inotify_poller.go:86 +0x91
github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0000ad180)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify/inotify.go:192 +0x18a
created by github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify.NewWatcher
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/fsnotify/fsnotify/inotify.go:59 +0x1a8

goroutine 9 [select, 13 minutes]:
github.com/lmorg/murex/builtins/events/onFileSystemChange.(*watch).init(0xc00002efc0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/events/onFileSystemChange/filesystem_unix.go:145 +0x125
created by github.com/lmorg/murex/builtins/events/onFileSystemChange.init.0
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/events/onFileSystemChange/filesystem_unix.go:28 +0x9f

goroutine 10 [sleep]:
runtime.goparkunlock(...)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        /usr/local/Cellar/go/1.12.4/libexec/src/runtime/time.go:105 +0x159
github.com/lmorg/murex/builtins/events/onSecondsElapsed.(*timer).init(0xc000123260)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/events/onSecondsElapsed/timer.go:44 +0x183
created by github.com/lmorg/murex/builtins/events/onSecondsElapsed.init.0
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/events/onSecondsElapsed/timer.go:19 +0xe6

goroutine 439 [chan receive, 13 minutes]:
github.com/lmorg/murex/shell.SignalHandler.func1(0xc00053ae40, 0x1)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/signals_unix.go:25 +0x58
created by github.com/lmorg/murex/shell.SignalHandler
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/signals_unix.go:23 +0x120

goroutine 7588 [runnable]:
github.com/lmorg/murex/vendor/github.com/lmorg/readline.DelayedTabContext.AppendSuggestions(0xc000101180, 0xa0f3c0, 0xc00002e200, 0xc0003e6500, 0xc0008c6000, 0x55cf, 0x6000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/timer.go:48 +0x155
github.com/lmorg/murex/shell/autocomplete.matchFilesystem.func1(0xc0006ec5b0, 0xa0f440, 0xc00069a4e0, 0x0, 0x0, 0x88f201, 0xc0005ce0e0, 0xa0f440, 0xc00069a060, 0xc000454000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/autocomplete/paths.go:72 +0x394
```

**Comment by lmorg** [comment]
Not an issue. Turns out the machine was running an out of date version of murex. Unable to replicate in newer versions but there's been a few improvements to concurrency since then
