### ISSUE TITLE
`=>` panics when used at start of pipeline

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#215]
There is already a test written:
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^(TestParserPipeIn)$

--- FAIL: TestParserPipeIn (0.00s)
panic: runtime error: slice bounds out of range [:-1] [recovered]
	panic: runtime error: slice bounds out of range [:-1]

goroutine 26 [running]:
testing.tRunner.func1(0xc000156400)
	/usr/local/Cellar/go/1.13.7/libexec/src/testing/testing.go:874 +0x3a3
panic(0x152d0a0, 0xc0000db940)
	/usr/local/Cellar/go/1.13.7/libexec/src/runtime/panic.go:679 +0x1b2
github.com/lmorg/murex/lang.parser(0xc000052bd8, 0x5, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/parser.go:590 +0xa6b1
github.com/lmorg/murex/lang.testParserSimple(0xc000156400, 0xc0000d1db0, 0x9, 0x9)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/parser_test.go:134 +0x10b
github.com/lmorg/murex/lang.TestParserPipeIn(0xc000156400)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/parser_pipe_test.go:86 +0x332
testing.tRunner(0xc000156400, 0x15c77d8)
	/usr/local/Cellar/go/1.13.7/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.7/libexec/src/testing/testing.go:960 +0x350
exit status 2
FAIL	github.com/lmorg/murex/lang	0.215s
```

**Comment by lmorg** [comment]
I've fixed this bug and added some additional parser and compiler testing to flush out a few more similar bugs relating to misuse of pipes but which should have been handled gracefully.
