### ISSUE TITLE
readline: panic

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#248]
```
panic: runtime error: slice bounds out of range [6:3]
(builtin) no doc written
goroutine 1 [running]:
github.com/lmorg/murex/shell/autocomplete.matchPartialFlags(0xc000210f00, 0xc00078e7a0, 0x6, 0xc00089a0f0)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/autocomplete/flags.go:236 +0x333
github.com/lmorg/murex/shell/autocomplete.match(0xc000210f00, 0xc00078e7a0, 0x6, 0xc00078e740, 0x4, 0xc00078d020, 0x0, 0x2, 0x0, 0xc00089a0f0, ...)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/autocomplete/flags.go:97 +0x50
github.com/lmorg/murex/shell/autocomplete.matchFlags(0xc000210f00, 0x1, 0x4, 0x0, 0x0, 0xc00078e740, 0x4, 0xc00078d020, 0x2, 0x2, ...)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/autocomplete/flags.go:189 +0x3b1
github.com/lmorg/murex/shell/autocomplete.MatchFlags(...)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/autocomplete/autocomplete.go:107
github.com/lmorg/murex/shell.tabCompletion(0xc000695000, 0xc, 0x400, 0xc, 0xc00011b400, 0x162be80, 0xc0007d8900, 0xc000786690, 0x1, 0x900000400, ...)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/tab.go:58 +0x741
github.com/lmorg/murex/utils/readline.(*Instance).getTabCompletion(0xc00011b400)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/utils/readline/tab.go:37 +0x131
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc00011b400, 0x0, 0x0, 0x0, 0x0)
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/utils/readline/readline.go:171 +0xbbf
github.com/lmorg/murex/shell.ShowPrompt()
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/shell.go:119 +0x1c1
github.com/lmorg/murex/shell.Start()
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/shell/shell.go:69 +0x1d4
main.startMurex()
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/main.go:153 +0x200
main.main()
        /Users/laurencemorgan/Documents/dev/go/src/github.com/lmorg/murex/main.go:36 +0xca
```

**Comment by lmorg** [comment]
Missing the following in `flags.go`
```
if !strings.HasPrefix(flag, partial) {
	continue
}
```

It's such a small change that I'm just going to roll this up as part of a larger update happening later this week with breaking changes to `test`
