### ISSUE TITLE
`:q` crashes the shell

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#254]
Both when using the interractive shell:
```
~ » :q                                                                          
~ » panic: runtime error: index out of range [1] with length 1                  

goroutine 1 [running]:
github.com/lmorg/murex/shell/history.noColon(0xc0006dd950, 0x2, 0xc0006dd950, 0x2)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/history/colon.go:7 +0x363
github.com/lmorg/murex/shell/history.expandHistBangBang(0xc0006dda8d, 0x0, 0xc00011f400, 0x3, 0x153888b, 0x1, 0xffffffffffffffff)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/history/vars.go:80 +0x75
github.com/lmorg/murex/shell/history.expandVariables(0x195eae0, 0x0, 0x0, 0xc00011f400, 0x0, 0x0, 0x120, 0x118, 0x1, 0x2)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/history/vars.go:68 +0x130
github.com/lmorg/murex/shell/history.ExpandVariables(...)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/history/vars.go:37
github.com/lmorg/murex/shell.hintExpandVariables(0x195eae0, 0x0, 0x0, 0x1, 0x0, 0x46)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/hint.go:120 +0x6e
github.com/lmorg/murex/shell.hintText(0x195eae0, 0x0, 0x0, 0x0, 0x149a860, 0x1, 0xc000447b20)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/hint.go:33 +0x5d
github.com/lmorg/murex/utils/readline.(*Instance).getHintText(0xc00011f400)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/hint.go:9 +0xb2
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc00011f400, 0x0, 0x0, 0x0, 0x0)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/readline.go:53 +0x317
github.com/lmorg/murex/shell.ShowPrompt()
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:119 +0x1c1
github.com/lmorg/murex/shell.Start()
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:69 +0x1d4
main.startMurex()
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:153 +0x200
main.main()
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:36 +0xca
```

...and again when starting the shell due to `:q` existing in `~/.murex_history`. 

This looks a real simple bug to fix and should be included in the next push to `master`

**Comment by lmorg** [comment]
Patched in 8a9a6b46dcb7150e00bc1a96bb4e98971fb88c85 -- soon to be merged into dev (and hopefully prod before Monday).

I expect this will come with a massive jump in version number too ;)
