### ISSUE TITLE
readline: runtime error: slice bounds out of range [21:18]

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#255]
```
panic: runtime error: slice bounds out of range [21:18]

goroutine 2684 [running]:
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).writeTabGrid(0xc00011b400)
        /go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/tabgrid.go:150 +0x563
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).writeTabCompletion(0xc00011b400)
        /go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/tab.go:82 +0x75
github.com/lmorg/murex/vendor/github.com/lmorg/readline.(*Instance).renderHelpers(0xc00011b400)
        /go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/update.go:170 +0x3d
github.com/lmorg/murex/vendor/github.com/lmorg/readline.DelayedTabContext.AppendSuggestions(0xc00011b400, 0xa1d000, 0xc000608940, 0xc0002eccc0, 0xc000bc8000, 0x4b18, 0x4c00)
        /go/src/github.com/lmorg/murex/vendor/github.com/lmorg/readline/timer.go:56 +0x2fa
github.com/lmorg/murex/shell/autocomplete.matchFilesystem.func1(0xc0009763c0, 0xa1d080, 0xc0004f2ea0, 0xc0009d452a, 0x3, 0x88da01, 0xc000206be0, 0xa1d080, 0xc0004f2e40, 0xc000736d20)
        /go/src/github.com/lmorg/murex/shell/autocomplete/paths.go:72 +0x3d4
created by github.com/lmorg/murex/shell/autocomplete.matchFilesystem
        /go/src/github.com/lmorg/murex/shell/autocomplete/paths.go
```

**Comment by lmorg** [comment]
Error relates to this code:
```
		caption := rl.tcPrefix + suggestions[i]
		if len(caption) > rl.tcMaxLength {
			var s string
			switch {
			case len(caption) < iCellWidth:
				s = caption
			case len(caption)-iCellWidth+6 < 1:
				s = caption[:iCellWidth-1] + "…"
			default:
				//s := caption[:4] + "…" + caption[len(caption)-rl.tcMaxLength:]
				s = caption[:4] + "…" + caption[len(caption)-iCellWidth+6:]
			}
			caption = s
		}
```

it's pretty ugly code so I've moved it into its own function and added some extremely rudimentary fuzz checking:
```
func cropCaption(caption string, tcMaxLength int, iCellWidth int) string {
	switch {
	case iCellWidth == 0:
		// this condition shouldn't ever happen but lets cover it just in case
		return ""
	case len(caption) > tcMaxLength:
		return caption
	case len(caption) < 5:
		return caption
	case len(caption) < iCellWidth:
		return caption
	case len(caption)-iCellWidth+6 < 1:
		return caption[:iCellWidth-1] + "…"
	case len(caption) > 5+len(caption)-iCellWidth+6:
		return caption[:4] + "…" + caption[len(caption)-iCellWidth+6:]
	default:
		return caption[:iCellWidth-1] + "…"
	}
}
```
```
package readline

import (
	"strings"
	"testing"

	"github.com/lmorg/murex/test/count"
)

func TestCropCaption(t *testing.T) {
	// We aren't really bothered about the quality of the output here, just
	// testing that the function doesn't generate any slice out of bounds
	// exceptions

	var caption, maxLen, cellWidth int

	defer func() {
		if r := recover(); r != nil {
			t.Errorf("Panic raised on iteration %d,%d,%d: %s", caption, maxLen, cellWidth, r)
		}
	}()

	for caption = 0; caption < 101; caption++ {
		for maxLen = 0; maxLen < 101; maxLen++ {
			for cellWidth = 0; cellWidth < 101; cellWidth++ {
				cropCaption(strings.Repeat("s", caption), maxLen, cellWidth)
			}
		}
	}

	count.Tests(t, caption*maxLen*cellWidth)
}
```
