### ISSUE TITLE
panic in readline

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#341]
This happened by chance when ctrl+u while in vim mode. Unable to recreate it.
```
» panic: runtime error: slice bounds out of range [1:0]
-- DELETE --
goroutine 1 [running]:
github.com/lmorg/murex/utils/readline.(*Instance).viDeleteByAdjust(0xc0001d0580, 0x1)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/vimdelete.go:66 +0x594
github.com/lmorg/murex/utils/readline.(*Instance).vimDelete(0xc0001d0580, 0xc000f7c000, 0x1, 0x100000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/vimdelete.go:21 +0x27a
github.com/lmorg/murex/utils/readline.(*Instance).readlineInput(0xc0001d0580, 0xc000f7c000, 0x1, 0x100000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/readline.go:402 +0x1f1
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc0001d0580, 0x0, 0x0, 0x0, 0x0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/readline.go:235 +0xa8f
github.com/lmorg/murex/shell.ShowPrompt()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:113 +0x19e
github.com/lmorg/murex/shell.Start()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:64 +0x14c
main.startMurex()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:155 +0x20a
main.main()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:38 +0xcc
```

**Comment by lmorg** [comment]
Just happened again. Looks like typing `d` (in `debug`) causes it to fail in vim mode
```
panic: runtime error: slice bounds out of range [-1:]
-- DELETE --
goroutine 1 [running]:
github.com/lmorg/murex/utils/readline.(*Instance).viDeleteByAdjust(0xc000206580, 0x1)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/vimdelete.go:62 +0x5b8
github.com/lmorg/murex/utils/readline.(*Instance).vimDelete(0xc000206580, 0xc00085e000, 0x1, 0x100000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/vimdelete.go:21 +0x27a
github.com/lmorg/murex/utils/readline.(*Instance).readlineInput(0xc000206580, 0xc00085e000, 0x1, 0x100000)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/readline.go:402 +0x1f1
github.com/lmorg/murex/utils/readline.(*Instance).Readline(0xc000206580, 0x0, 0x0, 0x0, 0x0)
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/readline/readline.go:235 +0xa8f
github.com/lmorg/murex/shell.ShowPrompt()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:113 +0x19e
github.com/lmorg/murex/shell.Start()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/shell/shell.go:64 +0x14c
main.startMurex()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:155 +0x20a
main.main()
        /Users/laurencemorgan/go/src/github.com/lmorg/murex/main.go:38 +0xcc
```

**Comment by lmorg** [comment]
Fix written and merged to master
