### ISSUE TITLE
Panic in mxjson parser

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#352]
```
panic: runtime error: index out of range [-1]

goroutine 565 [running]:
github.com/lmorg/murex/utils/mxjson.(*nestedObject).GetObjType(...)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/mxjson/structs.go:210
github.com/lmorg/murex/utils/mxjson.Parse(0xc00057e0a0, 0x97, 0xa0, 0x46e8c80, 0xc00014a018, 0x48b96e0, 0xc00014a030)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/mxjson/parser.go:379 +0x575d
github.com/lmorg/murex/utils/json.UnmarshalMurex(0xc00057e0a0, 0x97, 0xa0, 0x46e8c80, 0xc00014a018, 0xa0, 0x0)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/utils/json/unmarshal.go:34 +0xad
github.com/lmorg/murex/builtins/core/autocomplete.set(0xc000240c60, 0x0, 0xc00056de9c)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/core/autocomplete/autocomplete.go:91 +0x16e
github.com/lmorg/murex/builtins/core/autocomplete.cmdAutocomplete(0xc000240c60, 0xc00009a840, 0xc00056de80)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/builtins/core/autocomplete/autocomplete.go:29 +0x106
github.com/lmorg/murex/lang.executeProcess(0xc000240c60)
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/process.go:268 +0xdac
created by github.com/lmorg/murex/lang.runModeNormal
	/Users/laurencemorgan/go/src/github.com/lmorg/murex/lang/interpreter_pc.go:65 +0x7e
```

Code which (i believe) triggered it:

```
autocomplete set awsume {
    [{
        "DynamicDesc": ({ autocomplete.asumepy }),
        "optional": true
    }],
    [{
        "Dynamic": ({ autocomplete.awscon })
    }]
}
```

**Comment by lmorg** [comment]
Fixed in dev
