### ISSUE TITLE
panic inside `event`

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#414]
```
panic: fileRef should not be nil value
goroutine 8 [running]:
github.com/lmorg/murex/builtins/events.Callback({0xc0005ee280, 0x0}, {0xa29500, 0xc001164840}, {0xc000ad8c00, 0x0, 0x0}, 0x0, {0xba5f78, 0xc00002ce10})
    /home/lau/dev/go/src/github.com/lmorg/murex/builtins/events/handler.go:34 +0x48b
github.com/lmorg/murex/builtins/events/onFileSystemChange.(*watch).init(0xc000081240)
    /home/lau/dev/go/src/github.com/lmorg/murex/builtins/events/onFileSystemChange/filesystem_unix.go:148 +0x247
created by github.com/lmorg/murex/builtins/events/onFileSystemChange.init.0
    /home/lau/dev/go/src/github.com/lmorg/murex/builtins/events/onFileSystemChange/filesystem_unix.go:28 +0xb3
```

This was triggered via:

```
event onFileSystemChange tffmt=${pwd} { terraform: fmt ${pwd} }
```

**Comment by lmorg** [comment]
Fixed in `devel`. Will be merged to master in next release
