### ISSUE TITLE
Panic in `event`: with zero length parameter

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#418]
```
event onFileSystemChange example= { code }
```
Panics:
```
panic: runtime error: index out of range [0] with length 0
goroutine 1681 [running]:
github.com/lmorg/murex/builtins/events/onFileSystemChange.(*watch).Add(0xc000075220, {0xc00038c730, 0x5}, {0xc00038c730, 0x41ab42}, {0xc0001d6b40, 0x18, 0x18}, 0xc00033fa10)
    /home/lau/dev/go/src/github.com/lmorg/murex/builtins/events/onFileSystemChange/filesystem_unix.go:91 +0x2bb
github.com/lmorg/murex/builtins/events.cmdEvent(0xc00027d200)
    /home/lau/dev/go/src/github.com/lmorg/murex/builtins/events/cmd.go:49 +0x246
github.com/lmorg/murex/lang.executeProcess(0xc00027d200)
    /home/lau/dev/go/src/github.com/lmorg/murex/lang/process.go:311 +0x69b
created by github.com/lmorg/murex/lang.runModeNormal
    /home/lau/dev/go/src/github.com/lmorg/murex/lang/interpreter_pc.go:66 +0x65
```

**Comment by lmorg** [comment]
Fix in `develop` -- will be pushed to `master` in the next release
